<a href="https://colab.research.google.com/github/yukudaa/Machine_Learning/blob/main/201858028_%EC%9D%B4%EC%9C%A0%EA%B5%AC2%EC%9E%A5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#201858028 이유구
import numpy as np # used for handling numbers
import pandas as pd # used for handling the dataset
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
from sklearn.impute import SimpleImputer #used for handling missing data
from sklearn.preprocessing import LabelEncoder # used for encoding categorical 
from sklearn.model_selection import train_test_split # used for splitting training
from sklearn.preprocessing import StandardScaler # used for featuer scalling

In [ ]:
dataset = pd.read_csv('DataPreprocessing.csv')
X = dataset.iloc[:, :-1].values 
Y = dataset.iloc[:, -1].values

In [ ]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(X[:, 1:])
X[:, 1:] = imputer.transform(X[:, 1:])

In [ ]:
#201858028 이유구
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])

In [ ]:
labelencoder_X.classes_

array(['Brazil', 'India', 'USA'], dtype=object)

In [ ]:
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [ ]:
labelencoder_X.inverse_transform(list(X[:, 0]))

array(['India', 'Brazil', 'USA', 'Brazil', 'USA', 'India', 'Brazil',
       'India', 'USA', 'India'], dtype=object)

In [ ]:
#201858028 이유구
labelencoder_Y = LabelEncoder()
Y = labelencoder_Y.fit_transform(Y)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
minmax_scaler = MinMaxScaler()
X[: ,1:] = minmax_scaler.fit_transform(X[:,1:])
print(X)

[[1 0.7391304347826089 0.6857142857142859]
 [0 0.0 0.0]
 [2 0.13043478260869557 0.17142857142857149]
 [0 0.4782608695652173 0.37142857142857144]
 [2 0.5652173913043479 0.45079365079365075]
 [1 0.34782608695652173 0.2857142857142858]
 [0 0.5120772946859904 0.11428571428571432]
 [1 0.9130434782608696 0.8857142857142857]
 [2 1.0 1.0]
 [1 0.4347826086956521 0.5428571428571429]]
